name = "stocktracker-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "*/5 4-8 * * *"
]

[[d1_databases]]
binding = "DB"
database_name = "stocktracker-db"
database_id = "e5a97f51-35a1-42cd-b6ad-e55e95fa21cd"

[vars]
JWT_SECRET = "stocktracker-jwt-secret-change-in-production"
CORS_ORIGIN = "*"
