ALTER TABLE stocks ADD COLUMN bvps REAL DEFAULT 0;
ALTER TABLE stocks ADD COLUMN dps REAL DEFAULT 0;
ALTER TABLE stocks ADD COLUMN roe REAL DEFAULT 0;
ALTER TABLE stocks ADD COLUMN payout_ratio REAL DEFAULT 0;
ALTER TABLE stocks ADD COLUMN req_rate_of_return REAL DEFAULT 0.12;
ALTER TABLE stocks ADD COLUMN growth_rate REAL DEFAULT 0;
